### ISSUE TITLE
java.lang.RuntimeException: com.twitter.chill.config.ConfigurationException: Could not find class for: com.twitter.scalding.serialization.KryoHadoop

### ISSUE THREAD

**Issue by nikolovivan** [tresata/spark-scalding#2]
I've been playing with the library quite a lot in the last few days. As I mentioned in my previous question, my final goal is to read some data written to HDFS using scalding in SequenceFiles and serialized with kryo and then process them in Spark.

I've been doing some changes to the library internally, but generally I have the following changes (which could be hacky for now, but as long as it starts working, I could propose them in a pull request):

```
class RichSource(val source: Source, configuration: Configuration = new Configuration) {
  def spark(implicit sc: SparkContext): FieldsRDD = CascadingRDD(sc, source, configuration)
}

abstract class SparkJob(args: Args) extends Job(args) {
  def hadoopConf: Configuration = {
    val res = mode match {
      case hm: HadoopMode => hm.jobConf
      case _ => new Configuration()
    }
    config.foreach {
      case (key, value) => res.set(key.toString, value.toString)
    }
    res
  }

  private def tmpJars: Option[Seq[String]] = Option(hadoopConf.get("tmpjars")).map(_.split(",")) // re-use tmpjars in spark

  implicit def sourceToSparkRichSource(source: Source): RichSource = new RichSource(source, hadoopConf)

  implicit lazy val sc: SparkContext = newSc(ConfigFactory.load, name, tmpJars)

  override def run : Boolean
}
```

Basically my idea is to be able to pass whatever the Job `config` method sets to the application and use it. In my case I want to set different serializers, etc.

I end up with the following `io.serializations` option:

```
org.apache.hadoop.io.serializer.WritableSerialization,cascading.tuple.hadoop.TupleSerialization,org.apache.hadoop.io.serializer.JavaSerialization,com.twitter.chill.hadoop.KryoSerialization
```

The problem is that even though I have a fat jar and I can see that the `com.twitter.scalding.serialization.KryoHadoop` class is there, I still get the following stack trace:

```
15/01/28 16:03:00 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.RuntimeException: com.twitter.chill.config.ConfigurationException: Could not find class for: com.twitter.scalding.serialization.KryoHadoop
    at com.twitter.chill.hadoop.KryoSerialization.setConf(KryoSerialization.java:75)
    at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:73)
    at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
    at org.apache.hadoop.io.serializer.SerializationFactory.add(SerializationFactory.java:72)
    at org.apache.hadoop.io.serializer.SerializationFactory.<init>(SerializationFactory.java:63)
    at org.apache.hadoop.io.SequenceFile$Reader.init(SequenceFile.java:1942)
    at org.apache.hadoop.io.SequenceFile$Reader.initialize(SequenceFile.java:1810)
    at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1759)
    at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1773)
    at org.apache.hadoop.mapred.SequenceFileRecordReader.<init>(SequenceFileRecordReader.java:49)
    at org.apache.hadoop.mapred.SequenceFileInputFormat.getRecordReader(SequenceFileInputFormat.java:64)
    at com.tresata.spark.scalding.CascadingRDD.compute(CascadingRDD.scala:219)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
    at org.apache.spark.scheduler.Task.run(Task.scala:54)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.twitter.chill.config.ConfigurationException: Could not find class for: com.twitter.scalding.serialization.KryoHadoop
    at com.twitter.chill.config.ConfiguredInstantiator.<init>(ConfiguredInstantiator.java:62)
    at com.twitter.chill.hadoop.KryoSerialization.setConf(KryoSerialization.java:69)
    ... 22 more
Caused by: java.lang.ClassNotFoundException: com.twitter.scalding.serialization.KryoHadoop
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at com.twitter.chill.config.ConfiguredInstantiator.<init>(ConfiguredInstantiator.java:60)
    ... 23 more
15/01/28 16:03:00 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, ANY, 1356 bytes)
15/01/28 16:03:00 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
15/01/28 16:03:00 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.RuntimeException: com.twitter.chill.config.ConfigurationException: Could not find class for: com.twitter.scalding.serialization.KryoHadoop
        com.twitter.chill.hadoop.KryoSerialization.setConf(KryoSerialization.java:75)
        org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:73)
        org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        org.apache.hadoop.io.serializer.SerializationFactory.add(SerializationFactory.java:72)
        org.apache.hadoop.io.serializer.SerializationFactory.<init>(SerializationFactory.java:63)
        org.apache.hadoop.io.SequenceFile$Reader.init(SequenceFile.java:1942)
        org.apache.hadoop.io.SequenceFile$Reader.initialize(SequenceFile.java:1810)
        org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1759)
        org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1773)
        org.apache.hadoop.mapred.SequenceFileRecordReader.<init>(SequenceFileRecordReader.java:49)
        org.apache.hadoop.mapred.SequenceFileInputFormat.getRecordReader(SequenceFileInputFormat.java:64)
        com.tresata.spark.scalding.CascadingRDD.compute(CascadingRDD.scala:219)
        org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        java.lang.Thread.run(Thread.java:745)
15/01/28 16:03:00 ERROR TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
15/01/28 16:03:00 INFO TaskSchedulerImpl: Cancelling stage 0
15/01/28 16:03:00 INFO Executor: Executor is trying to kill task 1.0 in stage 0.0 (TID 1)
15/01/28 16:03:00 INFO TaskSchedulerImpl: Stage 0 was cancelled
15/01/28 16:03:00 INFO DAGScheduler: Failed to run runJob at CascadingRDD.scala:161
Exception in thread "main" java.lang.Throwable: If you know what exactly caused this error, please consider contributing to GitHub via following link.
https://github.com/twitter/scalding/wiki/Common-Exceptions-and-possible-reasons#orgapachesparksparkexception
    at com.twitter.scalding.Tool$.main(Tool.scala:132)
    at com.twitter.scalding.Tool.main(Tool.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:329)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.RuntimeException: com.twitter.chill.config.ConfigurationException: Could not find class for: com.twitter.scalding.serialization.KryoHadoop
        com.twitter.chill.hadoop.KryoSerialization.setConf(KryoSerialization.java:75)
        org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:73)
        org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        org.apache.hadoop.io.serializer.SerializationFactory.add(SerializationFactory.java:72)
        org.apache.hadoop.io.serializer.SerializationFactory.<init>(SerializationFactory.java:63)
        org.apache.hadoop.io.SequenceFile$Reader.init(SequenceFile.java:1942)
        org.apache.hadoop.io.SequenceFile$Reader.initialize(SequenceFile.java:1810)
        org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1759)
        org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1773)
        org.apache.hadoop.mapred.SequenceFileRecordReader.<init>(SequenceFileRecordReader.java:49)
        org.apache.hadoop.mapred.SequenceFileInputFormat.getRecordReader(SequenceFileInputFormat.java:64)
        com.tresata.spark.scalding.CascadingRDD.compute(CascadingRDD.scala:219)
        org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        java.lang.Thread.run(Thread.java:745)
Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1185)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1174)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1173)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1173)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:688)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1391)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
    at akka.actor.ActorCell.invoke(ActorCell.scala:456)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Seems like the class loader in `com.twitter.chill.config.ConfiguredInstantiator` doesn't see the classes in my jar.

I know that it might not be an issue with this library, but any pointers would be welcome. I've already tried so many things (copying `com.twitter.scalding.serialization.KryoHadoop`, explicitly adding chill as a dependency, etc., etc.) and I seem to be running out of ideas.

Thanks in advance!

**Comment by koertkuipers** [comment]
hey ivan,
which scalding source was used to write sequencefiles?
com.twitter.scalding.SequenceFile?

if you do not change anything with respect to serialization, what error do
you get when reading sequence files?

ideally spark should be able to handle writables with kryo out of the box.
if not then that sounds like a pullreq to me.

the serialization framework used is the one of spark, not scalding. so the
scalding serialization settings that you care about are the ones that go
into the SparkConf, and ultimately into the SparkContext. see section about
kryo here:
http://spark.apache.org/docs/1.2.0/tuning.html

currently SparkContext is created in SparkJob on this line:
implicit lazy val sc: SparkContext = newSc(ConfigFactory.load, name,
tmpJars)
we chose to use a typesafe config for these settings (which is what the
ConfigFactory.load is for).
so to modify these setting you need to create an application.conf that is
included in your jar.

let me do some experimentation with sequence files

**Comment by koertkuipers** [comment]
i havent tried/done anything yet, but a possible solution could be to always register a serializer for writables with kryo in spark.

see:
http://apache-spark-user-list.1001560.n3.nabble.com/Hadoop-Writable-and-Spark-serialization-td5721.html

so we would need something like this:
/*\* A Kryo serializer for Hadoop writables. copied from Shark sources */
class KryoWritableSerializer[T <: Writable] extends KSerializer[T] {
  override def write(kryo: Kryo, output: Output, writable: T) {
    val ouputStream = new DataOutputStream(output)
    writable.write(ouputStream)
  }

  override def read(kryo: Kryo, input: Input, cls: java.lang.Class[T]): T = {
    val writable = cls.newInstance()
    val inputStream = new DataInputStream(input)
    writable.readFields(inputStream)
    writable
  }
}  

and then in newSc function always register this KryoWritableSerializer:
sparkConf.registerKryoClasses(Seq(classOf[KryoWritableSerializer]))

**Comment by nikolovivan** [comment]
Hi Koert,

I might have tried some of the things you propose. I am away now, but will
check as soon as I get home or tomorrow morning.

**Comment by koertkuipers** [comment]
i did a quick test. i converted fruits.bsv to a sequence file, and ran the demo on that. it worked without issues.

this was the modified demo:

```
package com.tresata.spark.scalding.demo

import com.twitter.scalding.{ Args, Csv, SequenceFile }
import com.tresata.spark.scalding.SparkJob

class DemoSequenceFileJob(args: Args) extends SparkJob(args) {
  override def run: Boolean = {
    SequenceFile(args("input"), ('name, 'color, 'quantity)).spark.fieldsApi
      .discard('color)
      .groupBy('name){ _
        .sum[Int]('quantity)
        .size
    }
      .write(Csv(args("output"), separator = "|", writeHeader = true))
    true
  }
}
```

**Comment by nikolovivan** [comment]
Hey Koert,

I didn't mention something essential - my data is serialized into a custom class. I tried the SequenceFile example myself and indeed, it works. But consider the following:

Just a simple model class:

```
package com.tresata.spark.scalding.demo

/**
 * Created by inikolov on 29/01/15.
 */
case class FruitLine(name: String, color: String, quantity: Int)
```

A job to write the bsv into SequenceFiles of this model class:

```
package com.tresata.spark.scalding.demo

import com.twitter.scalding.{SequenceFile, Csv, Job, Args}

/**
 * Created by inikolov on 29/01/15.
 */
class DemoWriteSequenceClass(args: Args) extends Job(args) {

  Csv(args("input"), separator = "|", skipHeader = true)
    .mapTo(('name, 'color, 'quantity) -> 'fruitLine) {
      x: (String, String, String) =>
        val (name, color, quantity) = x
          FruitLine(name, color, quantity.toInt)
    }
    .write(SequenceFile(args("output")))
}
```

And finally, the spark job to transform the data:

```
package com.tresata.spark.scalding.demo

import com.tresata.spark.scalding.SparkJob
import com.twitter.scalding.{Csv, SequenceFile, Args}

/**
 * Created by inikolov on 29/01/15.
 */
class DemoJobSequenceClass(args: Args) extends SparkJob(args) {

  override def run: Boolean = {
    SequenceFile(args("input"), ('fruitLine)).spark.fieldsApi
      .mapTo('fruitLine -> ('name, 'color, 'quantity)) {
      x: FruitLine =>
        (x.name, x.color, x.quantity)
      }
      .discard('color)
      .groupBy('name) {
        _.sum[Int]('quantity).size
      }.write(Csv(args("output"), separator = "|", writeHeader = true))
    true
  }
}
```

Without modifying anything else, except specifying different Scalding and Spark versions (`0.11.1-cdh5` and `1.1.1` respectively) I get the following complete stack trace (for converting the data, chill is required):

```
15/01/29 07:53:50 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 0)
cascading.tuple.TupleException: unable to read from input identifier: 'unknown'
    at cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:127)
    at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:144)
    at org.apache.spark.Aggregator.combineValuesByKey(Aggregator.scala:58)
    at org.apache.spark.shuffle.hash.HashShuffleWriter.write(HashShuffleWriter.scala:55)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
    at org.apache.spark.scheduler.Task.run(Task.scala:54)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: cascading.CascadingException: unable to load deserializer for: com.tresata.spark.scalding.demo.FruitLine from: org.apache.hadoop.io.serializer.SerializationFactory
    at cascading.tuple.hadoop.TupleSerialization.getNewDeserializer(TupleSerialization.java:464)
    at cascading.tuple.hadoop.TupleSerialization$SerializationElementReader.getDeserializerFor(TupleSerialization.java:654)
    at cascading.tuple.hadoop.TupleSerialization$SerializationElementReader.read(TupleSerialization.java:621)
    at cascading.tuple.hadoop.io.HadoopTupleInputStream.readType(HadoopTupleInputStream.java:105)
    at cascading.tuple.hadoop.io.HadoopTupleInputStream.getNextElement(HadoopTupleInputStream.java:52)
    at cascading.tuple.io.TupleInputStream.readTuple(TupleInputStream.java:78)
    at cascading.tuple.hadoop.io.TupleDeserializer.deserialize(TupleDeserializer.java:40)
    at cascading.tuple.hadoop.io.TupleDeserializer.deserialize(TupleDeserializer.java:28)
    at org.apache.hadoop.io.SequenceFile$Reader.deserializeValue(SequenceFile.java:2244)
    at org.apache.hadoop.io.SequenceFile$Reader.getCurrentValue(SequenceFile.java:2217)
    at org.apache.hadoop.mapred.SequenceFileRecordReader.getCurrentValue(SequenceFileRecordReader.java:109)
    at org.apache.hadoop.mapred.SequenceFileRecordReader.next(SequenceFileRecordReader.java:84)
    at cascading.tap.hadoop.util.MeasuredRecordReader.next(MeasuredRecordReader.java:61)
    at cascading.scheme.hadoop.SequenceFile.source(SequenceFile.java:93)
    at cascading.tuple.TupleEntrySchemeIterator.getNext(TupleEntrySchemeIterator.java:140)
    at cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:120)
    ... 16 more
15/01/29 07:53:50 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 1, localhost, ANY, 1292 bytes)
15/01/29 07:53:50 INFO Executor: Running task 1.0 in stage 1.0 (TID 1)
15/01/29 07:53:50 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 0, localhost): cascading.tuple.TupleException: unable to read from input identifier: 'unknown'
        cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:127)
        scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:144)
        org.apache.spark.Aggregator.combineValuesByKey(Aggregator.scala:58)
        org.apache.spark.shuffle.hash.HashShuffleWriter.write(HashShuffleWriter.scala:55)
        org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        java.lang.Thread.run(Thread.java:745)
15/01/29 07:53:50 ERROR TaskSetManager: Task 0 in stage 1.0 failed 1 times; aborting job
15/01/29 07:53:50 INFO TaskSchedulerImpl: Cancelling stage 1
15/01/29 07:53:50 INFO TaskSchedulerImpl: Stage 1 was cancelled
15/01/29 07:53:50 INFO Executor: Executor is trying to kill task 1.0 in stage 1.0 (TID 1)
15/01/29 07:53:50 INFO DAGScheduler: Failed to run runJob at CascadingRDD.scala:161
Exception in thread "main" java.lang.Throwable: If you know what exactly caused this error, please consider contributing to GitHub via following link.
https://github.com/twitter/scalding/wiki/Common-Exceptions-and-possible-reasons#orgapachesparksparkexception
    at com.twitter.scalding.Tool$.main(Tool.scala:132)
    at com.twitter.scalding.Tool.main(Tool.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:329)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 0, localhost): cascading.tuple.TupleException: unable to read from input identifier: 'unknown'
        cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:127)
        scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:144)
        org.apache.spark.Aggregator.combineValuesByKey(Aggregator.scala:58)
        org.apache.spark.shuffle.hash.HashShuffleWriter.write(HashShuffleWriter.scala:55)
        org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        java.lang.Thread.run(Thread.java:745)
Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1185)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1174)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1173)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1173)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:688)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1391)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
    at akka.actor.ActorCell.invoke(ActorCell.scala:456)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Now, if I pass the configuration that Job creates (it adds some extra Kryo serializations in the `io.serializations` option) further to CascadingRDD, this is where it is not able to find the classes I explained above.

**Comment by koertkuipers** [comment]
i get what you are trying to so. this is indeed scalding (or really cascading/hadoop) serialization that is being used by the Cascading Scheme when it is reading data, so it's not spark serialization. and it is correct that Kryo is not registered at that point currently.

i am not sure why registering com.twitter.chill.hadoop.KryoSerialization leads to the "Could not find class for: com.twitter.scalding.serialization.KryoHadoop" exception. i am worried it is because com.twitter.chill.config.ConfiguredInstantiator (the one that does the class loading) is already loaded by spark (spark uses chill) and therefore has a different class-loader leading to the error. but that is just a guess. 

i will have some time later today to dig in some more.

**Comment by koertkuipers** [comment]
by the way, i find that Kryo is not very suitable for long term persistence, so generally i would avoid using it in scalding Sources (Cascading Taps).
same is true for Java Serialization...

**Comment by koertkuipers** [comment]
ok i got it to work by registering a custom version of KryoSerialization that does not use reflection but uses KryoHadoop directly. so the issue was indeed reflection. I can add my custom serializer to the package.

next we need to decide how the user should be able to set this. i am not sure i like an explicit hadoop Configuration object since it kills some of the "magic" of stuff like Csv(...).spark and fieldsApi.write(Csv(...))

i am hoping to automatically populate some settings in the Hadoop Configuration from the SparkConf. i believe spark does this too in some places.

**Comment by nikolovivan** [comment]
It looks like we are in different time zones and I'm always away when
you're around (writing from my phone now).

I don't like storing data in Kryo either, but this was not my call. The
data set I'm trying to use is produced by another team and I have to stick
with it or maybe duplicate it in a previous step in something easily
manageable.

Passing configs through the hadoop conf would be something like what I had
done, wouldn't it?

Did you pass the Kryo serialization the way Spark shows in their
documentation? With explicitly specifying classes and all?

I think that's the only thing I haven't tried yet, but I might be wrong.

**Comment by koertkuipers** [comment]
yes, i did basically the same thing as you did. except i end up with io.serializations being:
org.apache.hadoop.io.serializer.WritableSerialization,cascading.tuple.hadoop.TupleSerialization,com.tresata.spark.scalding.serialization.KryoSerialization

notice the custom serializer i am using for kryo. its the same as the one in chill except it doesn't rely on reflection, but instead always uses KryoHadoop. thats how i avoid the class not found exception that you had.

**Comment by nikolovivan** [comment]
Oh, I see!

In my case I implemented KryoHadoop myself, but it still used reflection.
That's why it didn't work.

I will give it a thought here. There could be a way to write a pull request
and be able to specify the class loader being used maybe.

It is still good enough this way as a workaround though. The problem is
that the class should be kept in sync with what the one in chill does.

**Comment by koertkuipers** [comment]
so the question remaining is what is the nicest way to allow the user to set this?
your approach is to use the Job.config, which is what a Scalding user would expect.

i am working on an alternative where you set it in the SparkConf. Basically any key in SparkConf spark.hadoop.<x>=<y> becomes <x>=<y> in Hadoop Configuration. this is more or less the convention that Spark chose for this. so this is what a Spark user would expect.

i will push a feature branch out and then we can compare, and see what's best way to go.

**Comment by koertkuipers** [comment]
yeah keeping KryoHadoop in sync will be a bit of a pain.

pushed the branch feat-cascading-serialization. so the only difference is that i rely on settings from SparkConf while you rely on settings from Job.config.
i have no strong preference but am leaning towards your approach, since Job.config is the first place most people would expect to find this setting.

**Comment by nikolovivan** [comment]
Yeah, I agree about the Job.config. Your approach is nice too, but as you said, it's more like how Spark people would do it.

I guess it's about agreeing and picking one of them. I personally don't mind either. I created a pull request. Have a look and let me know what you think.

**Comment by koertkuipers** [comment]
fixed in https://github.com/tresata/spark-scalding/pull/3
